# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: https://jamesegammon.com
baseurl: /
title: James Gammon


code: 
  title: code.Jamesegammon
  tagline: "creating and constructing."
  url: https://jamesegammon.com/code


film: 
  title: food.Jamesegammon
  tagline: Aiming to spread plentiful information on living with allergies 
  url: https://jamesegammon.com/food 


# INCLUDED FIELDS SHOULD BE PUT HERE
name: James Gammon
email: jamesegammon@gmail.com
description: Welcome! 
# Author is the default for posts, the atom feed, and is used in the footer. 
# Used in the _includes : footer 
author: James Gammon


# CUSTOM FIELDS SHOULD BE PUT HERE 
copyright: James Gammon. All rights reserved


# PUBLIC HANDLES
twitter_username: JamesGammon15
github_username:  jamesgammo
github:
  repo: https://github.com/jamesgammo/jamesgammo.github.io
  account: https://github.com/jamesgammo
 

# Build settings
#theme: minima
plugins:
- jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
